rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
before_script:
  - sh bootstrap
  - ruby extconf.rb
  - make
script: "export LD_LIBRARY_PATH=`rvm config-get libdir`:$LD_LIBRARY_PATH && rake"
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm:
        - 2.7
        - ruby-head
